### quick v2 request
GET https://localhost:5001/api/v2/products

### v2 request with pagination
GET https://localhost:5001/api/v2/products?page=3&size=100

### v2 request page out of range
GET https://localhost:5001/api/v2/products?page=35&size=100

### v2 request faulty pagination filter
GET https://localhost:5001/api/v2/products?page=3&size=ab

### Request by id
GET https://localhost:5001/api/v2/products/25


### Request by id not found
GET https://localhost:5001/api/v2/products/250000


### Request by id not found
GET https://localhost:5001/api/v2/products/-10

### Update description
Patch  https://localhost:5001/api/v2/products/25/
Content-Type: application/json
{"NewDescription":"test1"}

### Update description raw string body
Patch  https://localhost:5001/api/v2/products/25/description
Content-Type: application/json

test2